apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: cloud-volume
  resources:
    requests:
      storage: 5Gi
