apiVersion: v1
kind: Secret
metadata:
  name: cloudsecret
type: Opaque
stringData:
  NX_CLOUD_MONGO_SERVER_ENDPOINT: mongodb+srv://admin-user:DB_PASSWORD@cloud-mongodb-svc.mongodb.svc.cluster.local/nrwl-api?replicaSet=cloud-mongodb&ssl=false
  ADMIN_PASSWORD: SOME_ADMIN_PASSWORD
